service: crud-personas

provider:
  name: aws
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
      Resource: arn:aws:dynamodb:us-east-1:738256604744:table/user

functions:
  # Funciones Node.js
  deleteUser:
    handler: lambdas-node/handlers/deleteUser.deleteUser
    runtime: nodejs20.x
    events:
      - http:
          path: /users/{id}
          method: delete

  updateUser:
    handler: lambdas-node/handlers/updateUser.updateUser
    runtime: nodejs20.x
    events:
      - http:
          path: /users
          method: put

  # Funciones Java
  getUser:
    handler: com.serverless.GetUser
    runtime: java17
    package:
      artifact: lambdas-java/build/distributions/aws-java-simple-http-endpoint-1.0-SNAPSHOT.zip
    events:
      - http:
          path: /users/{id}
          method: get

  createUser:
    handler: com.serverless.CreateUser
    runtime: java17
    package:
      artifact: lambdas-java/build/distributions/aws-java-simple-http-endpoint-1.0-SNAPSHOT.zip
    events:
      - http:
          path: /users
          method: post
